import { useState } from 'react';
import { AlertCircle, ArrowRight, Check, LoaderCircle, LogOut, Pencil, Trash2, UserRound, X } from 'lucide-react';
import { deleteUserAccount, updateUserProfile, type AppUser } from '../lib/auth';

interface UserSettingsModalProps { user: AppUser; onClose: () => void; onUpdate: (user: AppUser) => void; onDelete: () => void; onLogout: () => void; }
export default function UserSettingsModal({ user, onClose, onUpdate, onDelete, onLogout }: UserSettingsModalProps) {
  const [mode, setMode] = useState<'menu' | 'edit' | 'delete'>('menu');
  const [name, setName] = useState(user.display_name); const [handle, setHandle] = useState(user.username);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const edit = async () => { setError(''); if (!name.trim() || !/^[a-z0-9._]+$/.test(handle.trim().toLowerCase())) return setError('راجعي الاسم واليوزر ثم حاولي مرة أخرى.'); setLoading(true); const result = await updateUserProfile(user, name, handle); setLoading(false); if (result.error || !result.user) setError(result.error || 'تعذر الحفظ.'); else onUpdate(result.user); };
  const remove = async () => { setLoading(true); const result = await deleteUserAccount(user); setLoading(false); if (!result.success) setError(result.error || 'تعذر الحذف.'); else onDelete(); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#3b3447]/50 p-4 backdrop-blur-sm" role="dialog" aria-modal="true">
    <div className="w-full max-w-md animate-rise rounded-[1.8rem] border border-[#ded3c5] bg-[#faf7f1] p-6 shadow-[0_28px_100px_rgba(59,52,71,.25)] sm:p-8" dir="rtl">
      <div className="mb-7 flex items-start justify-between"><div><p className="mb-2 font-mono text-[10px] uppercase tracking-[.2em] text-[#b82d49]">your space</p><h2 className="font-serif text-3xl text-[#3b3447]">{mode === 'menu' ? 'إعدادات الحساب' : mode === 'edit' ? 'تعديل الحساب' : 'حذف الحساب'}</h2></div><button aria-label="إغلاق" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl text-[#8e8178] hover:bg-[#eee7dc]"><X size={18} /></button></div>
      {mode === 'menu' && <div className="space-y-3"><div className="mb-5 flex items-center gap-3 rounded-2xl bg-[#eee7dc] p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#3b3447] text-[#f9f1e5]"><UserRound size={19} /></div><div><p className="font-semibold text-[#3b3447]">{user.display_name}</p><p dir="ltr" className="font-mono text-xs text-[#8e8178]">@{user.username}</p></div></div><button onClick={() => setMode('edit')} className="flex w-full items-center gap-3 rounded-xl border border-[#ddd2c4] bg-[#fffaf3] p-4 text-sm font-semibold text-[#514752] transition hover:border-[#b82d49]/30 hover:text-[#b82d49]"><Pencil size={17} /> تعديل البيانات <ArrowRight size={15} className="mr-auto rotate-180 text-[#a09288]" /></button><button onClick={onLogout} className="flex w-full items-center gap-3 rounded-xl border border-[#ddd2c4] bg-[#fffaf3] p-4 text-sm font-semibold text-[#514752] transition hover:border-[#9c6127]/30 hover:text-[#9c6127]"><LogOut size={17} /> تسجيل الخروج</button><button onClick={() => setMode('delete')} className="mt-5 flex w-full items-center gap-3 p-2 text-xs text-[#a09288] transition hover:text-[#b82d49]"><Trash2 size={15} /> حذف الحساب والرسائل نهائياً</button></div>}
      {mode === 'edit' && <div className="space-y-4"><div><label className="mb-2 block text-xs font-semibold text-[#6f625d]">الاسم الظاهر</label><input value={name} onChange={(event) => setName(event.target.value)} className="h-12 w-full rounded-xl border border-[#d7cec0] bg-[#fffdf9] px-4 text-sm outline-none focus:border-[#b82d49]" /></div><div><label className="mb-2 block text-xs font-semibold text-[#6f625d]">اليوزر</label><input dir="ltr" value={handle} onChange={(event) => setHandle(event.target.value)} className="h-12 w-full rounded-xl border border-[#d7cec0] bg-[#fffdf9] px-4 font-mono text-sm outline-none focus:border-[#b82d49]" /></div>{error && <Error text={error} />}<div className="flex gap-2 pt-2"><button onClick={() => setMode('menu')} className="h-12 flex-1 rounded-xl border border-[#d7cec0] text-sm text-[#6f625d]">رجوع</button><button disabled={loading} onClick={edit} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-[#b82d49] text-sm font-semibold text-[#fffaf2]">{loading ? <LoaderCircle size={17} className="animate-spin" /> : <><Check size={16} />حفظ</>}</button></div></div>}
      {mode === 'delete' && <div><div className="rounded-2xl border border-[#9c6127]/20 bg-[#fbf0df] p-4 text-sm leading-7 text-[#795127]"><p className="mb-1 font-semibold">هذا الإجراء نهائي</p>سيتم حذف حسابك وجميع الرسائل التي أرسلتِها. لا يمكن التراجع بعد التأكيد.</div>{error && <Error text={error} />}<div className="mt-5 flex gap-2"><button onClick={() => setMode('menu')} className="h-12 flex-1 rounded-xl border border-[#d7cec0] text-sm text-[#6f625d]">تراجعي</button><button disabled={loading} onClick={remove} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-[#b82d49]/30 bg-[#b82d49]/10 text-sm font-semibold text-[#a52540]">{loading ? <LoaderCircle size={17} className="animate-spin" /> : <><Trash2 size={16} />حذف نهائي</>}</button></div></div>}
    </div>
  </div>;
}
function Error({ text }: { text: string }) { return <div role="alert" className="flex gap-2 rounded-xl bg-[#b82d49]/8 p-3 text-xs leading-5 text-[#a52540]"><AlertCircle size={15} className="shrink-0" />{text}</div>; }